from .dashboard import dashboard_bp
from .sensors import sensors_bp
from .scans import scans_bp
from .chats import chat_bp
from .relay import relay_bp
from .weather import weather_bp
from .gallery import gallery_bp
from .telegram import telegram_bp
from .config_routes import config_bp
